repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(c|h)$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # or the corresponding release you prefer
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - python-dotenv
        args: ["--strict"]
